name: "Test pip install - multiple versions"
on:
  workflow_dispatch:
    inputs:
      python:
        description: "Python version to use"
        required: false
        type: string
        default: "3.11.13"
      ebs_gb:
        description: "EBS volume size in GB (default: 60)"
        required: false
        type: string
        default: "80"
permissions:
  id-token: write
  contents: read
jobs:
  installs:
    name: Test mamba_ssm==${{ matrix.mamba_version }} (torch=${{ matrix.torch_version }})
    strategy:
      matrix:
        include:
          - { "mamba_version": "2.2.0"     , torch_version: "2.4" }
          - { "mamba_version": "2.2.1"     , torch_version: "2.4" }
          - { "mamba_version": "2.2.2"     , torch_version: "2.4" }
          - { "mamba_version": "2.2.3post2", torch_version: "2.6" }
          - { "mamba_version": "2.2.4"     , torch_version: "2.6" }
          - { "mamba_version": "2.2.5"     , torch_version: "2.7" }
      fail-fast: false
    uses: ./.github/workflows/install.yaml
    secrets: inherit
    with:
      mamba_version: ${{ matrix.mamba_version }}
      torch_version: ${{ matrix.torch_version }}
      python: ${{ inputs.python }}
      ebs_gb: ${{ inputs.ebs_gb }}
